name: CI/CD

on:
  pull_request:
    branches: [develop, int, master]
  push:
    branches: [develop, int, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set Up project's NodeJS Version
        shell: bash -l {0}
        run: nvm install && nvm use

      - name: Check NodeJS and NPM Versions
        run: node --version && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Check Formatting
        run: npm run format:check

      - name: Test the application
        run: npm test -- --coverage
        env:
          CI: true

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
