name: CI/CD

on:
  pull_request:
    branches: [develop, int, master]
  push:
    branches: [develop, int, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set Up project's NodeJS Version
        shell: bash -l {0}
        run: nvm install && nvm use

      - name: Check NodeJS and NPM Versions
        run: node --version && npm --version

      - name: Cache dependencies
        uses: actions/cache@v3.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tdms-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-tdms-

      - name: Install dependencies
        run: npm ci

      # - name: Check for insecure dependencies
      #   run: npm audit --audit-level=moderate

      - name: Check Formatting
        run: npm run format:check

      - name: Test the application
        run: npm test -- --coverage
        env:
          CI: true

      - name: Build the app
        run: npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: npx surge --project ./build --domain https://bouncy-amusement.surge.sh/
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
