name: CI/CD

on:
  pull_request:
    branches: [CINOWIO-26055, develop, int, master]
  push:
    branches: [CINOWIO-26055, develop, int, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set Up project's NodeJS Version
        shell: bash -l {0}
        run: nvm install && nvm use

      - name: Check NodeJS and NPM Versions
        run: node --version && npm --version

      - name: Branch name
        run: echo ${{ github.ref_name }}

      - name: Branch name2
        run: echo ${{ github.ref }}

      - name: Cache dependencies
        uses: actions/cache@v3.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tdms-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-tdms-

      - name: Install dependencies
        run: npm ci

      # - name: Check for insecure dependencies
      #   run: npm audit --audit-level=moderate

      - name: Check Formatting
        run: npm run format:check

      - name: Test the application
        run: npm test -- --coverage
        env:
          CI: true

      - name: Install Surge
        run: npm install -g surge

      - name: Remove Snapshot from package version
        if: github.ref == 'refs/heads/master'
        run: sed -i -r 's/-SNAPSHOT//g' package.json

      - name: Run BD scan
        run: echo BD scan

      - name: Set ENV variable
        id: env
        if: contains(fromJSON('["develop", "int", "master", "CINOWIO-26055"]'), github.ref_name)
        shell: bash
        run: |
          echo 'NODE_VERSION=$(cat .nvmrc)'
          case "${{ github.ref_name }}" in
            "develop")
              echo 'BUILD_TARGET=dev' >> "${GITHUB_ENV}"
              echo 'TARGET_NAME=development' >> "${GITHUB_ENV}"
              ;;
            "int")
              echo "BUILD_TARGET=int" >> "${GITHUB_ENV}"
              echo 'TARGET_NAME=integration' >> "${GITHUB_ENV}"
              ;;
            "master")
              echo "BUILD_TARGET=" >> "${GITHUB_ENV}"
              echo 'TARGET_NAME=production' >> "${GITHUB_ENV}"
              ;;
          esac

      - name: Show "BUILD_TARGET"
        run: echo ${{ steps.env.outputs.BUILD_TARGET }} && echo nodeVersion is "${{ env.NODE_VERSION }}" && echo BUILD_TARGET is "${{ env.BUILD_TARGET }}"

      - name: Run SonarQube SCAN
        run: npm run "build${BUILD_TARGET:+:${BUILD_TARGET}}"
        env:
          BUILD_TARGET: ${{ env.BUILD_TARGET }}

      - name: Show "BUILD_TARGET2"
        run: echo ${{ steps.env.outputs.BUILD_TARGET }}

      - name: Build with ${{ env.BUILD_TARGET }} configuration
        if: contains(fromJSON('["develop", "int", "master", "CINOWIO-26055"]'), github.ref_name)
        run: echo npm run ${{ format('build{0}{1}', env.BUILD_TARGET && ':' || '', env.BUILD_TARGET || '') }}
        env:
          BUILD_TARGET: ${{ env.BUILD_TARGET }}
          COLON: ":"

      - name: Publish Artifact
        run: echo Publish Artifact

      # - name: Trigger Dev deployment
      #   if: github.ref == 'refs/heads/develop'
      #   run: npx surge --project ./build --domain https://bouncy-amusement.surge.sh/
      #   env:
      #     SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      #     SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      # - name: Trigger Int deployment
      #   if: github.ref == 'refs/heads/int'
      #   run: npx surge --project ./build --domain https://bouncy-amusement.surge.sh/
      #   env:
      #     SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      #     SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      # - name: Trigger Prod deployment
      #   if: github.ref == 'refs/heads/master'
      #   run: npx surge --project ./build --domain https://bouncy-amusement.surge.sh/
      #   env:
      #     SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      #     SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Send Notification to MS Teams
        run: echo Send Notification to MS Teams

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Show Java Verions
        run: java --version

      - name: Install Maven
        run: |
          wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xvf apache-maven-3.6.3-bin.tar.gz
          mv apache-maven-3.6.3 /opt/
          M2_HOME='/opt/apache-maven-3.6.3'
          PATH="$M2_HOME/bin:$PATH"
          export PATH
      - name: Show Maven Version
        run: mvn -version
